<?php $this->layout('layout::default', ['title' => 'About me']) ?>

<header class="intro-header" style="background-image: url('/img/about-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>About Me</h1>
                    <hr class="small">
                    <span class="subheading">This is what I do</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
            <p>My name is <strong>Enrico Zimuel</strong> and I’m a Full-Stack Developer since 1996. I'm specialized in web technologies and secure software. I've <?php echo date("Y") - 1999;?>+ years' experience with PHP and GNU/Linux. I also developed in C/C++, Java, Processing, Perl, Python, Javascript, AngularJS, and Node.js.</p>
            <p>Starting from 2008, I work as <i>Senior Software Engineer</i> in the R&amp;D department of <a href="http://www.zend.com/">Zend Technologies</a>, a Rogue Wave Company (USA). I worked as consultant for international companies such as ADP, Albacom, DHL, Enel, Engineering, Ericsson, FIAT, NIIT, Prisacom, Santander, and more.</p>
            <p>I'm an open source contributor: <a href="https://apigility.org/">Apigility</a>, <a href="https://docs.zendframework.com/zend-expressive/">Expressive</a>, <a href="https://framework.zend.com/">Zend Framework</a>, <a href="https://zenroom.dyne.org/">Zenroom - crypto language VM</a>, and more.</p>
            <p>I did academic research in Computer Science at <a href="http://ivi.uva.nl/">Informatics Institute</a> of Amsterdam University, <a href="/publications">here</a> you can find a list of my publications.</p>
            <p>Starting from 2018, I'm an Adjunct Professor at <a href="http://www.its-ictpiemonte.it/index_en.html">ITS ICT Piemonte</a>, teaching <i>Cloud Services</i> for software development technologies course.</p>
            <p>I'm a <a href="https://www.youtube.com/watch?v=SienrLY40-w">TEDx</a> and international speakers with <a href="/conferences">80+ talks</a> about web programming, computer security, and creative coding. I am a PHP and Zend Framework <a href="http://www.zend.com/en/services/certification/zend-certified-engineer-directory#ClientCandidateID=ZEND007791&cid=0">Certified Architect</a> and a member of the <a href="http://www.zend.com/services/certification/framework/education-advisory-board">Zend Education Advisory Board</a>.</p>
            <p>I wrote some books about web programming, open source, and applied cryptography, <a href="/books">here</a> you can find the full list.</p>
            <p>I got a B.Sc. honors degree in Computer Science and Economics from the <a href="http://en.unich.it/">University of Pescara</a> (Italy). I attended NKS 2006 school of <a href="https://en.wikipedia.org/wiki/Stephen_Wolfram">Stephen Wolfram</a> at Brown University (USA) and I participated in <a href="http://www.bigdive.eu/big-dive-second-edition/">Big Dive 2013</a>, a postgraduate course in Big Data and Data Visualization.</p>
            <p>I'm the co-founder of <a href="http://torino.grusp.org/">PHP User Group of Turin</a>, the city where I live with my wife and my son. I'm a 100% remote worker since 2008.</p>
        </div>
    </div>
  </div>
</div>
