<?php $this->layout('layout::default', ['title' => 'About me']) ?>

<header class="intro-header" style="background-image: url('/img/about-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>About Me</h1>
                    <hr class="small">
                    <span class="subheading">This is what I do</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
            <p>My name is <strong>Enrico Zimuel</strong> and I've been writing code since 1996. I'm an <a href="https://github.com/ezimuel">open source contributor</a> specialized in web technologies and applied cryptography. I'm a core member of PHP Framework Interop Group (<a href="https://www.php-fig.org/">PHP-FIG</a>) and longtime contributor of PHP community. I've been mentioned in the <a href="https://www.jetbrains.com/lp/php-25/">25 years of PHP</a> by JetBrains. In my career I used many computer languages including C/C++, Delphi, Java, Javascript, Lua, Node.js, Perl, PHP, Python, Visual Basic, x86 Assembly.</p>
            <p>I'm <i>Principal Software Engineer</i> at <a href="https://www.elastic.co/">Elastic</a>. Previously, I worked 11+ years for <a href="https://www.zend.com/">Zend Technologies</a>, the PHP company. I have been a consultant for international companies such as ADP, Albacom, DHL, Enel, Engineering, Ericsson, FCA, NIIT, Prisacom, Santander, and more.</p>
            <p>I did academic research in Computer Science at <a href="https://ivi.uva.nl/">Informatics Institute</a> of Amsterdam University, <a href="/publications">here</a> a list of my publications.</p>
            <p>I'm <i>Adjunct Professor</i> at <a href="https://www.unito.it/">University of Turin</a> and <a href="https://www.its-ictpiemonte.it/">ITS ICT Piemonte</a> since 2018. I have taught the following courses: <i>Blockchain technologies</i>, <i>Cloud services</i>, <i>Modern Data Architecture</i>, <i>NoSQL databases</i> and <i>PHP programming</i>.</p>
            <p>I'm <a href="https://www.youtube.com/watch?v=SienrLY40-w">TEDx</a> and international speaker with <a href="/conferences">120 talks</a> about web programming, computer security and creative coding.</p>
            <p>I wrote <a href="/books">some books</a> about web programming, open source, secure software and applied cryptography.</p>
            <p>I got a B.Sc. honors degree in Computer Science and Economics from the <a href="https://en.unich.it/">University of Pescara</a> (Italy). I attended NKS 2006 school of <a href="https://en.wikipedia.org/wiki/Stephen_Wolfram">Stephen Wolfram</a> at Brown University (USA) and I participated in <a href="https://www.bigdive.eu/bigdive2/">Big Dive 2013</a>, a postgraduate course in Big Data and Visualization, using Python and D3.js.</p>
            <p>I'm the co-founder of <a href="http://torino.grusp.org/">PHP User Group of Turin</a>, the city where I live. I'm 100% remote worker since 2008.</p>
        </div>
    </div>
  </div>
</div>
