<?php $this->layout('layout::default', ['title' => 'Books']) ?>

<header class="intro-header" style="background-image: url('/img/books-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Books</h1>
                    <hr class="small">
                    <span class="subheading">I wrote some books (or contributed to)</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading books">
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="https://www.tecnichenuove.com/libri/strumenti-di-informatica" target="_blank"><img src="/img/strumentinformatica.jpg" class="book" alt="Strumenti di Informatica"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Strumenti di Informatica</h3>
              <h4>Un approccio moderno per corsi universitari</h4>
              <p><i>Enrico Zimuel</i></p>
              <p>A modern introduction to computer science for university students and not only.</p>
              <p>
                <a href="http://www.tecnichenuove.com">Tecniche Nuove</a>, Milano, pp. 400, 2025, ISBN 9788848147613<br>
                <a href="https://www.strumentinformatica.it/" target="_blank">Booksite</a> – <a href="https://www.tecnichenuove.com/libri/strumenti-di-informatica" target="_blank">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
                <div class="col-md-4 col-sm-4">
                  <br />
                  <a href="https://www.tecnichenuove.com/prodotto/sviluppare-in-php-7-ii-edizione/?affiliates=25" target="_blank"><img src="/img/sviluppare_php7_ii.jpg" class="book" alt="Sviluppare in PHP 7"></a>
                </div>
                <div class="col-md-8 col-sm-8">
                  <h3>Sviluppare in PHP 7 (II edizione)</h3>
                  <h4>Realizzare applicazioni web e API professionali</h4>
                  <p><i>Enrico Zimuel</i></p>
                  <p>Second edition of the book "Sviluppare in PHP 7". The book contains the new features of PHP 7.4 and a new chapter about design patterns in PHP.</p>
                  <p>
                    <a href="http://www.tecnichenuove.com">Tecniche Nuove</a>, Milano, pp. 432, 2019, ISBN 9788848140317<br>
                    <a href="https://www.sviluppareinphp7.it/" target="_blank">Booksite</a> – <a href="https://www.tecnichenuove.com/prodotto/sviluppare-in-php-7-ii-edizione/?affiliates=25" target="_blank">Buy online</a>
                  </p>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-4 col-sm-4">
                  <br />
                  <a href="https://amzn.to/2rPnJdK" target="_blank"><img src="/img/cloud_essentials.png" class="book" alt="Cloud Essentials"></a>
                </div>
                <div class="col-md-8 col-sm-8">
                  <h3>Cloud essentials</h3>
                  <h4>Un viaggio nel cloud computing</h4>
                  <p><i>Gabriele Mittica, Walter Dal Mut</i></p>
                  <p>A book about cloud computing. The book starts from the basic of cloud computing and introduces all the modern technologies, mainly using Amazon Web Services. I wrote the Preface of the book and it contains an interview about me as open source contributor.</p>
                  <p>Amazon.it, pp. 317, 2018, ISBN 9781980705468<br>
                    <a href="https://cloudessentials.it/" target="_blank">Booksite</a> – <a href="https://amzn.to/2rPnJdK" target="_blank">Buy online</a>
                  </p>
                </div>
            </div>
            <br />
          <div class="row">
              <div class="col-md-4 col-sm-4">
                <br />
                <a href="https://amzn.to/2DAnUfI" target="_blank"><img src="/img/sviluppare_php7.jpg" class="book" alt="Sviluppare in PHP 7"></a>
              </div>
              <div class="col-md-8 col-sm-8">
                <h3>Sviluppare in PHP 7</h3>
                <h4>Realizzare applicazioni web e API professionali</h4>
                <p><i>Enrico Zimuel</i></p>
                <p>A book about professional web development in PHP 7. The book starts from the basic of the language and introduces all the modern techniques to build web applications and API using the latest features of PHP until version 7.2.</p>
                <p>
                  <a href="http://www.tecnichenuove.com">Tecniche Nuove</a>, Milano, pp. 352, 2017, ISBN 978848131209<br>
                  <a href="https://www.sviluppareinphp7.it/" target="_blank">Booksite</a> – <a href="https://amzn.to/2DAnUfI" target="_blank">Buy online</a>
                </p>
              </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="https://amzn.to/35WwZf8" target="_blank"><img src="/img/js_best_practices.jpg" class="book" alt="Javascript Best Practices"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Programmare con Javascript. Best practices</h3>
              <p><i>Matteo Collina, Francesco Fullone, Federico Galassi, Enrico Zimuel</i></p>
              <p>A collection of Javascript best practices to develop web applications from a professional point of view. Some of the topics: Test the code with Mocha and Zombie.js, Node.js, CoffeeScript, Design Pattern, Performance.</p>
              <p>
                <a href="http://www.fag.it/">FAG Edizioni</a>, Milano, pp. 240, 2013, ISBN 9788866043164<br>
                <a href="http://www.jsbestpractices.it/" target="_blank">Booksite</a> – <a href="https://amzn.to/35WwZf8" target="_blank">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="https://amzn.to/2OJxP8Y"><img src="img/php_best_practices.jpg" class="book" alt="PHP Best Practices"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Programmare con PHP. Best practices</h3>
              <p><i>AA.VV.</i></p>
              <p>A collection of PHP best practices to develop web applications from a professional point of view. Some of the topics: PHP 5.4, Code refactoring, Cloud services, REST API, Security, Test Driven Development, Performance, Continuous Integration. I wrote the Chapters 2, 5, 7 and 9.</p>
              <p>
                <a href="http://www.fag.it/">FAG Edizioni</a>, Milano, pp. 544, 2012, ISBN 9788866042303<br>
                <a href="http://www.phpbestpractices.it/" target="_blank">Booksite</a> – <a href="https://amzn.to/2OJxP8Y">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="https://www.tecnichenuove.com/prodotto/come-si-fa-a-usare-la-firma-digitale/?affiliates=25"><img src="/img/firma_digitale.jpg" class="book" alt="Come si fa a usare la firma digitale"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Come si fa a usare la firma digitale</h3>
              <p><i>Andrea Battistella, Enrico Zimuel</i></p>
              <p>A book about the applications of the electronic signatures in Italian law with pratical and technical aspects. The books shows also the usage of the most used software for the digital signature.</p>
              <p>
                <a href="http://www.tecnichenuove.com/">Tecniche Nuove</a>, Milano, pp. 125, 2010, ISBN 9788848124607<br>
                <a href="https://www.tecnichenuove.com/prodotto/come-si-fa-a-usare-la-firma-digitale/?affiliates=25">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="http://www.amazon.it/gp/product/8820341727/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8820341727&amp;linkCode=as2&amp;tag=365filmitunam-21"><img src="/img/sicurezza_codice.jpg" class="book"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Sicurezza del codice</h3>
              <p><i>Alessandro Sinibaldi</i></p>
              <p>How to write secure software? This book explain the approach to secure programming in different use cases. I wrote Chapter 5 about secure software in PHP.</p>
              <p>
                <a href="http://www.hoepli.it/">Hoepli</a>, Milano, pp. 370, 2008, ISBN 9788820341725<br>
                <a href="http://www.amazon.it/gp/product/8820341727/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8820341727&amp;linkCode=as2&amp;tag=365filmitunam-21">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="http://www.amazon.it/gp/product/8850321546/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8850321546&amp;linkCode=as2&amp;tag=365filmitunam-21"><img src="/img/revolution_os.jpg" class="book"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Revolution OS. Voci dal codice libero</h3>
              <p><i>AA. VV.</i></p>
              <p>Revolution OS is a 2001 documentary film that traces the twenty-year history of GNU, Linux, open source, and the free software movement. This is the Italian translation of the original documentary with a book that contains a glossary of the technical terms used in the documentary. I collaborated to write this book.</p>
              <p>
                <a href="http://www.apogeonline.com/">Apogeo</a>, Milano, 85 minutes DVD, pp. 142 book, 2003, ISBN 9788850321544<br>
                <a href="http://www.amazon.it/gp/product/8850321546/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8850321546&amp;linkCode=as2&amp;tag=365filmitunam-21">Buy online</a>
              </p>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <br />
              <a href="http://www.amazon.it/gp/product/8873034837/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8873034837&amp;linkCode=as2&amp;tag=365filmitunam-21"><img src="/img/segreti_spie.jpg" class="book"></a>
            </div>
            <div class="col-md-8 col-sm-8">
              <h3>Segreti, Spie e Codici Cifrati</h3>
              <p><i>Corrado Giustozzi, Andrea Monti, Enrico Zimuel</i></p>
              <p>A book about cryptography from three different perspectives: historical, law and technical. I wrote the technical part of the book with some example of cryptographic systems and their cryptoanalysis (with software examples included in the CDROM attached to the book).</p>
              <p>
                <a href="http://www.apogeonline.com/">Apogeo</a>, Milano, pp. 450, 2003 (second edition), ISBN 9788873034834<br>
                <a href="/doc/appendice.pdf">Appendix</a> (not included in the book) – <a href="http://www.amazon.it/gp/product/8873034837/ref=as_li_tf_tl?ie=UTF8&amp;camp=3370&amp;creative=23322&amp;creativeASIN=8873034837&amp;linkCode=as2&amp;tag=365filmitunam-21">Buy online</a>
              </p>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
