<?php $this->layout('layout::default', ['title' => 'Conferences']) ?>

<header class="intro-header" style="background-image: url('/img/conferences-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Conferences</h1>
                    <hr class="small">
                    <span class="subheading">Speaking in conferences since 2000</span>
                </div>
            </div>
        </div>
    </div>
</header>


<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="page-heading">
  			<p>Here you can find an extract of my talks, collected by year, with slides and videos.</p>
        <h2>2018</h2>
        <ol>
          <li value="89"><strong>Develop web APIs in PHP using middleware with Expressive</strong> (<a href="/slides/codeeurope2018">slides</a>)<br />
              <a href="https://www.codeeurope.pl/en">Code Europe</a> 2018 - Warsaw (Poland)
          </li>
        </ol>
        <h2>2017</h2>
        <ol>
          <li value="88"><strong>Sviluppare applicazioni web professionali in PHP 7</strong> (<a href="/slides/unito2017">slides</a> in Italian)<br />
              <a href="https://www.unito.it/">University of Turin</a> – Computer Science Department - Turin (Italy)
          </li>
          <li value="87"><strong>Sviluppo di Progressive Web App con PHP 7</strong> (<a href="/slides/webappconf2017">slides</a> in Italian)<br />
              <a href="http://2017.webappconf.it">WebAppConf</a> 2017 – Turin (Italy)
          </li>
          <li value="86"><strong>Encryption, authentication and data integrity in PHP 7</strong> (<a href="/slides/phpce2017">slides</a> - <a href="https://www.youtube.com/watch?v=KMrB7MJ5SmU">video</a>)<br />
              <a href="https://2017.phpce.eu/">PHP Central Europe</a> 2017 – Rawa Mazowiecka (Poland)
          </li>
          <li value="85"><strong>Building Middleware Web APIs in PHP 7 with Expressive</strong> (<a href="/slides/zendcon2017/api-tutorial">slides</a>)<br />
              <strong>Design Security in PHP using Middleware</strong> (<a href="/slides/zendcon2017/design-security-middleware">slides</a>)<br />
              <strong>The most exciting features of PHP 7.1</strong> (<a href="/slides/zendcon2017/php71">slides</a>)<br />
              <a href="http://www.zendcon.com/">ZendCon</a> 2017 – Las Vegas NV (USA)
          </li>
          <li value="84"><strong>Developing Web APIs using Middleware in PHP 7</strong> (<a href="/slides/apiconf2017">slides</a> - <a href="http://video.html.it/sviluppo-di-web-api-middleware-in-php-7-con-expressive/">video</a>)<br />
              <a href="http://2017.apiconf.it/">APIConf</a> 2017 – Turin (Italy)
          </li>
          <li value="83"><strong>The most exciting features of PHP 7.1</strong> (<a href="/slides/phpday2017/php71">slides</a> - <a href="https://vimeo.com/237702599">video</a>)<br />
              <strong>Building middleware applications with Zend Framework 3</strong><br />
          <a href="http://2017.phpday.it/">PHP Day</a> 2017 – Verona (Italy)
          </li>
          <li value="82"><strong>Developing middleware web APIs in PHP 7</strong> (<a href="/slides/cloudconf2017">slides</a> - <a href="http://video.html.it/developing-middleware-web-apis-in-php-7/">video</a>)<br>
          <a href="http://2017.cloudconf.it/">CloudConf</a> 2017 – Turin (Italy)
          </li>
        </ol>
        <h2>2016</h2>
        <ol>
          <li value="81"><strong>The new features of PHP 7</strong> (<a href="/slides/codemotion2016">slides</a> – <a href="https://www.youtube.com/watch?v=dJBHwN1V_-M">video</a>)<br>
          <a href="http://milan2016.codemotionworld.com/">Codemotion</a> 2016 – Milan (Italy)
          </li>
          <li value="80"><strong>Build Middleware applications with Zend Framework 3</strong> (<a href="/slides/zendcon2016/middleware">slides</a> – <a href="https://github.com/ezimuel/zend-expressive-workshop">github</a>)<br>
          <strong>Build web APIs using Zend Expressive</strong> (<a href="/slides/zendcon2016/expressive-api">slides</a>)<br>
          <strong>Encryption, authentication and data integrity in PHP 7</strong> (<a href="/slides/zendcon2016/encrypt">slides</a>)<br>
          <a href="http://www.zendcon.com/">ZendCon</a> 2016 – Las Vegas NV (USA)
          </li>
          <li value="79"><strong>Build Middleware applications with Zend Framework 3</strong> (<a href="/slides/phpday2016">slides</a> – <a href="https://vimeo.com/176067284">video</a>)<br>
          <a href="http://2016.phpday.it/">PHP Day</a> 2016 – Verona (Italy)
          </li>
          <li value="78"><strong>Build Middleware applications with Zend Framework 3</strong> (<a href="/slides/midwestphp2016/expressive">slides</a>)<br>
          <strong>Encryption, authentication and data integrity in PHP</strong> (<a href="/slides/midwestphp2016/encryption">slides</a>)<br>
          <a href="http://2016.midwestphp.org/">Midwest PHP conference</a> 2016 – Minneapolis MN (USA)
          </li>
          <li value="77"><strong>Develop RESTful API in PHP using Apigility</strong> (<a href="/slides/phpbenelux2016/workshop">slides</a>)<br>
          <strong>Encryption, authentication and data integrity in PHP</strong> (<a href="/slides/phpbenelux2016/encryption">slides</a>)<br>
          <a href="https://conference.phpbenelux.eu/2016/">PHP Benelux conference</a> 2016 – Antwerp (Belgium)
          </li>
        </ol>
        <h2>2015</h2>
        <ol>
          <li value="76"><strong>Develop RESTful API in PHP using Apigility</strong> (<a href="/slides/phpsummer2015">slides</a> – <a href="https://github.com/ezimuel/php-summercamp-apigility">github</a>)<br>
          <a href="http://2015.phpsummercamp.com">PHP Summer Camp</a> 2015 – Rovinj (Croazia)
          </li>
          <li value="75"><strong>Pushing boundaries: Zend Framework 3 and the future</strong> (<a href="/slides/phpday2015">slides</a> – <a href="https://vimeo.com/channels/phpday/134859190">video</a>)<br>
          <a href="http://2015.phpday.it/">PHP Day</a> 2015 – Verona (Italy)
          </li>
          <li value="74"><strong>Pushing boundaries: Zend Framework 3 and the future</strong> (<a href="https://www.youtube.com/watch?v=r9UmNQ2Famo">video</a>)<br>
          <a href="http://www.afup.org/pages/phptourluxembourg2015/">PHP Tour</a> 2015 – Luxembourg City (Luxembourg)
          </li>
          <li value="73"><strong>PHP 7: upcoming features</strong> (<a href="/slides/pugtorino/php7">slides</a>)<br>
          <a href="http://torino.grusp.org">PUG Torino</a> 2015 – Turin (Italy)
          </li>
          <li value="72"><strong>Develop and design RESTful web API in PHP using Apigility</strong> (<a href="/slides/codemotion2015">slides</a> – <a href="https://www.youtube.com/watch?v=5SfefG76CG4">video</a>)<br>
          <a href="http://rome2015.codemotionworld.com">Codemotion</a> 2015 – Rome (Italy)
          </li>
          <li value="71"><strong>API authentication with OAuth2 in the cloud</strong> (<a href="https://speakerdeck.com/ezimuel/api-authentication-with-oauth2-in-the-cloud">slides</a>)<br>
          <a href="http://2015.cloudconf.it/">CloudConf</a> 2015 – Turin (Italy)
          </li>
        </ol>
        <h2>2014</h2>
        <ol>
          <li value="70"><strong>Information Security in PHP: the CIA Triad Approach</strong> (<a href="https://speakerdeck.com/ezimuel/information-security-in-php-the-cia-triad-approach">slides</a>)<br>
          <strong>API authentication with OAuth2 and Apigility</strong> (<a href="https://speakerdeck.com/ezimuel/api-authentication-with-oauth2-and-apigility">slides</a>)<br>
          <a href="http://www.zendcon.com/">ZendCon</a> 2014 – Santa Clara (USA)
          </li>
          <li value="69"><strong>Encryption, authentication and data integrity in PHP</strong> (<a href="/slides/dpc2014">slides</a>)<br>
          <a href="http://www.phpconference.nl/">Dutch PHP Conference</a> 2014 – Amsterdam (The Netherlands)
          </li>
          <li value="68"><strong>API RESTful (and RPC) for PHP with Apigility</strong> (<a href="/slides/phpday2014">slides</a> – <a href="https://vimeo.com/channels/phpday/127240684">video</a>)<br>
          <a href="http://2014.phpday.it/">phpDay</a> 2014 – Verona (Italy)
          </li>
          <li value="67"><strong>Experiments in code, generative art in Javascript</strong> (<a href="https://speakerdeck.com/ezimuel/experiments-in-code-generative-art-in-javascript">slides</a>)<br>
          <a href="http://2014.jsday.it/">jsDay</a> 2014 – Verona (Italy)
          </li>
          <li value="66"><strong>API development: problems, solutions, and best practices</strong> (<a href="/slides/apidaysberlin2014">slides</a>)<br>
          <a href="http://berlin.apidays.io/">APIdays Berlin</a> 2014 – Berlin (Germany)
          </li>
          <li value="65"><strong>RESTful API development: problems and solutions</strong> (<a href="/slides/cloudconf2014">slides</a>)<br>
          <a href="http://www.cloudconf.it/">Cloud Conference</a> 2014 – Turin (Italy)
          </li>
          <li value="64"><strong>Creative programming with Open Source softwares</strong> (<a href="https://speakerdeck.com/ezimuel/creative-programming-with-open-source-softwares">slides</a>)<br>
          <a href="http://www.pescaralug.org/">LUG Pescara</a> &amp; <a href="http://www.newfolder.it/">New Folder</a> –  Club Maze – Pescara (Italy)
          </li>
          <li value="63"><strong>Apigility, the API builder for PHP</strong> (<a href="https://speakerdeck.com/ezimuel/apigility-the-api-builder-for-php">slides</a>)<br>
          <a href="http://2014.zfday.it/">Zend Framework Day</a> 2014 – Turin (Italy)
          </li>
        </ol>
        <h2>2013</h2>
        <ol>
          <li value="62"><strong>Symfony2 and Zend Framework 2: the perfect team</strong> (<a href="https://speakerdeck.com/ezimuel/symfony2-and-zend-framework-2-the-perfect-team">slides</a> – <a href="http://www.youtube.com/watch?v=eMPE6qRSMwI">video</a>)<br>
          <a href="http://www.afup.org/pages/forumphp2013/">PHP Forum</a> 2013 – Paris (France)
          </li>
          <li value="61"><strong>A PHP micro framework for HTTP API client</strong> (<a href="https://speakerdeck.com/ezimuel/a-php-micro-framework-for-http-api-client">slides</a>)<br>
          <a href="http://europe.zendcon.com/">ZendCon Europe</a> 2013 – Paris (France)
          </li>
          <li value="60"><strong>Do you speak design patterns in PHP?</strong> (<a href="https://speakerdeck.com/ezimuel/do-you-speak-design-patterns-in-php">slides</a>)<br>
          <strong>Building secure applications using Zend Framework 2</strong> (<a href="https://speakerdeck.com/ezimuel/building-secure-applications-with-zend-framework-2">slides</a>)<br>
          <strong>Use OpenStack with Zend Framework 2</strong> (<a href="https://speakerdeck.com/ezimuel/use-openstack-with-zend-framework-2">slides</a>)<br>
          <a href="http://www.zendcon.com">ZendCon</a> 2013 – Santa Clara (USA)
          </li>
          <li value="59"><strong>Creative Programming: the art to create using a computer language</strong> (<a href="https://www.youtube.com/watch?v=SienrLY40-w">video</a>)<br>
          <a href="http://www.tedxcrocetta.com">TEDx Crocetta</a> 2013 – Turin (Italy)
          </li>
          <li value="58"><strong>Programmazione creativa con Processing</strong> (<a href="https://speakerdeck.com/ezimuel/programmazione-creativa-con-processing">slides</a> in Italian)<br>
          <a href="http://2013.digitalfestival.net/">Digital Festival</a> 2013 – Turin (Italy)
          </li>
          <li value="57"><strong>Zend Framework 2 and Symfony2: The perfect team</strong><br>
          <strong>Build a Zend Framework 2 application in less than a talk </strong> (<a href="http://vimeo.com/78263154">video</a>)<br>
          <a href="http://2013.phpday.it/">phpDay</a> 2013 – Verona (Italy)
          </li>
          <li value="56"><strong>Zend Developer Cloud: PHP development in the cloud</strong> (<a href="https://speakerdeck.com/ezimuel/zend-developer-cloud-php-development-in-the-cloud">slides</a>)<br>
          <a href="http://www.cloudconf.it/">Cloud Conference</a> 2013 – Turin (Italy)
          </li>
          <li value="55"><strong>MVC Events and Module: the New Architecture of Zend Framework 2</strong> (<a href="https://speakerdeck.com/ezimuel/mvc-plus-events-plus-modules-the-new-architecture-of-zf2">slides</a> – <a href="https://www.youtube.com/watch?v=O6dwYklDVp0">video</a>)<br>
          <a href="http://phpconference.co.uk/">PHP UK Conference</a> 2013 – London (UK)
          </li>
          <li value="54"><strong>Sviluppo di applicazioni web sicure con Zend Framework 2</strong> (<a href="https://speakerdeck.com/ezimuel/sviluppo-di-applicazioni-web-sicure-con-zf2">slides</a> in Italian)<br>
          <a href="http://www.zfday.it">Zend Framework Day</a> 2013 – Milan (Italy)
          </li>
        </ol>
        <h2>2012</h2>
        <ol>
          <li value="53"><strong>Design web applications using ZF2</strong><br>
          <strong>Building secure web applications with ZF2</strong><br>
          <a href="http://phpconference.ge/">International PHP Conference</a> 2012 – Tbilisi (Georgia)
          </li>
          <li value="52"><strong>Zend Framework 2 per lo sviluppo di applicazioni web</strong> (<a href="https://speakerdeck.com/ezimuel/zend-framework-2-per-lo-sviluppo-di-applicazioni-web">slides</a> in Italian)<br>
          <a href="http://venezia.codemotion.it/">Codemotion</a> 2012 – Venice (Italy)
          </li>
          <li value="51"><strong>Design Pattern Bootcamp</strong> (<a href="https://speakerdeck.com/ezimuel/design-patterns-bootcamp">slides</a>)<br>
          <strong>Cryptography made easy with ZF2</strong> (<a href="https://speakerdeck.com/ezimuel/cryptography-made-easy-with-zend-framework-2">slides</a>)<br>
          <strong>ZF2 and Symfony2: the perfect team</strong> (<a href="https://speakerdeck.com/skoop/zend-framework-2-and-symfony2-the-perfect-team-zendcon">slides</a>)<br>
          <a href="http://www.zendcon.com">ZendCon</a> 2012 – Santa Clara (USA)
          </li>
          <li value="50"><strong>A quick start on Zend Framework 2</strong> (<a href="http://www.slideshare.net/e.zimuel/quick-start-on-zend-framework-2" target="_blank">slides</a> – <a href="http://www.youtube.com/watch?v=gkxkS1zIFGU">audio</a>)<br>
          <a href="http://www.phpconference.nl/">Dutch PHP Conference</a> 2012 – Amsterdam (The Netherlands)
          </li>
          <li value="49"><strong>A quick start on Zend Framework 2</strong> (<a href="">slides</a> – <a href="http://www.youtube.com/watch?v=GSSMbshwDnA">video</a>) <br>
          <a href="http://afup.org/pages/forumphp2013/">PHP Forum Paris</a> 2012 – Paris (France)
          </li>
          <li value="48"><strong>Password security: how to generate and store passwords in a secure way</strong> (<a href="http://www.slideshare.net/e.zimuel/password-insecurity">slides</a>)<br>
          <a href="http://moca.olografix.org/moca2012">Metro Olografix Hacker Camp</a> 2012 – Pescara (Italy)
          </li>
          <li value="47"><strong>Come integrare Zend Framework in WordPress</strong> (<a href="http://es.slideshare.net/e.zimuel/integrare-zend-framework-in-wordpress">slides</a> in Italian)<br>
          <a href="http://www.wpcon.it">WordPress Conference</a> 2012 – Turin (Italy)
          </li>
          <li value="46"><strong>Le novità di Zend Framework 2</strong> (<a href="http://vimeo.com/48518173">video</a> in Italian)<br>
          <a href="http://eventi.html.it/releaseparty/">HTML.it</a> Release Party – Roma (Italy)
          </li>
          <li value="45"><strong>A quick start on Zend Framework 2</strong> (<a href="http://www.slideshare.net/e.zimuel/a-quick-start-on-zend-framework-2" target="_blank">slides</a>)<br>
          <a href="http://2012.phpday.it/">phpDay</a> 2012 – Verona (Italy)
          </li>
          <li value="44"><strong>Zend Framework 2 quick start</strong> (<a href="http://www.slideshare.net/e.zimuel/zend-framework-2-quick-start" target="_blank">slides</a> – <a href="http://www.youtube.com/watch?v=pkePMvHOiIw">video</a>)<br>
          <a href="http://www.zfconf.ru/">ZFConf</a> 2012 – Moscow (Russia)
          </li>
          <li value="43"><strong>Develop mobile web application with Zend Framework</strong> (<a href="http://www.slideshare.net/e.zimuel/php-goes-mobile" target="_blank">slides</a> in Italian)<br>
          <a href="http://mobilephp.grusp.org/">PHP Goes Mobile</a> 2012 – Milan (Italy)
          </li>
        </ol>
        <h2>2011</h2>
        <ol>
          <li value="42"><strong>Zend Framework 2: state of the art</strong><br>
          <a href="">PHP Tour Lille</a> 2011 – Lille (France)
          </li>
          <li value="41"><strong>Cryptography in PHP: use cases</strong> (<a href="http://www.slideshare.net/e.zimuel/cryptography-in-php-use-cases">slides</a>) <br>
          <a href="http://www.zendcon.com">ZendCon</a> 2011 – Santa Clara (USA)
          </li>
          <li value="40"><strong>Manage cloud infrastructures in PHP using Zend Framework 2 (and ZF1)</strong> (<a href="http://www.slideshare.net/e.zimuel/manage-cloud-infrastructures-using-zend-framework-2-and-zf1" target="_blank">slides</a>)<br>
          <a href="http://phpconference.com">International PHP Conference</a> 2011 – Mainz (Germany)
          </li>
          <li value="39"><strong>Zend Framework 2: state of the art</strong><br>
          <a href="http://conference.phpnw.org.uk">PHP North West</a> 2011 – Manchester (UK)
          </li>
          <li value="38"><strong>Strong cryptography in PHP</strong> (<a href="http://www.slideshare.net/e.zimuel/strong-cryptography-in-php" target="_blank">Slideshare</a>)<br>
          <a href="http://www.phpconference.nl/">Dutch PHP Conference</a> 2011 – Amsterdam (The Netherlands)
          </li>
          <li value="37"><strong>Introduzione alla PEC: le regole tecniche</strong> (<a href="http://www.slideshare.net/e.zimuel/introduzione-alla-posta-elettronica-certificata-pec-le-regole-tecniche" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.science.unitn.it/~sala/events2011/pec.html">CrittoPEC</a> 2011  – Department of Mathematics, University of Trento (Italy)
          </li>
          <li value="36"><strong>Leveraging the open source applications ecosystem with IBM i</strong><br>
          <a href="http://www.comeur.net">Common Europe Conference</a> 2011 – Milan (Italy)
          </li>
          <li value="35"><strong>Zend Framework 2.0</strong><br>
          <a href="http://2011.phpday.it/">phpDay</a> 2011 – Verona (Italy)
          </li>
        </ol>
        <h2>2010</h2>
        <ol>
          <li value="34"><strong>Simple Cloud API: accesso semplificato al cloud computing</strong><br>
          <a href="">WebTech Conference</a> 2010 – Milano (Italy)
          </li>
          <li value="33"><strong>How to scale PHP applications</strong> (<a href="http://www.slideshare.net/e.zimuel/how-to-scale-php-applications" target="_blank">slides</a>)<br>
          <a href="http://phpconference.es/">PHP Barcelona Conference</a> 2010 – Barcelona (Spain)
          </li>
          <li value="32"><strong>Business value of PHP</strong><br>
          <a href="http://www.data3.se/">Data3 Conference</a> 2010 – Utsikten, Nynashamn (Sweden)
          </li>
          <li value="31"><strong>Velocizzare Joomla! con Zend Server Community Edition</strong> (<a href="http://www.slideshare.net/e.zimuel/joomla-con-zsce" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.joomladay.it/">JoomlaDay</a> 2010 – Verona (Italy)
          </li>
          <li value="30"><strong>Getting started with PHP on IBM i</strong><br>
          <a href="http://www.comeur.net/">Common Europe Conference</a> 2010 – Stratford-upon-Avon (UK)
          </li>
          <li value="29"><strong>Caching in PHP: get better performance for your web applications</strong><br>
          <a href="http://www.phpday.it">PHPDay</a> 2010 – Corropoli, Teramo (Italy)
          </li>
        </ol>
        <h2>2009</h2>
        <ol>
          <li value="28"><strong>Zend_Cache: how to improve the performance of PHP applications</strong> (<a href="/talks/Zend_Cache.pdf" target="_blank">slides</a><a>)<br>
          </a><a href="http://phpconference.es/">PHP Barcelona Conference</a> 2009 – Barcelona (Spain)
          </li>
          <li value="27"><strong>Zend_Dojo: l’integrazione della libreria Dojo nello Zend Framework</strong><br>
          <a href="#">PHPCon</a> 2009 – Roma (Italy)
          </li>
        </ol>
        <h2>2008</h2>
        <ol>
          <li value="26"><strong>Architecting &amp; Building a Multi-Country Mobile User Community</strong><br>
          <a href="http://www.zendcon.com">Zend PHP Conference &amp; Expo</a> 2008 – Santa Clara (USA)
          </li>
          <li value="25"><strong>La firma digitale e le sue possibili applicazioni</strong> (<a href="/talks/csig_2008.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.csig.eu/">Centro Studi Informatica Giuridica</a> 2008 – Pescara (Italy)
          </li>
        </ol>
        <h2>2007</h2>
        <ol>
          <li value="24"><strong>La sicurezza delle applicazioni in PHP</strong> (<a href="/talks/phpday_2007.pdf" target="_blank">slides</a> in Italian – <a href="http://www.youtube.com/watch?v=eTiDLB5ekQU">video</a> in Italian)<br>
          <a href="">PHPDay</a> 2007 – Verona (Italy)
          </li>
        </ol>
        <h2>2006</h2>
        <ol>
          <li value="23"><strong>XCheck: a platform for benchmarking XQuery engines (demonstration)</strong><br>
          <a href="http://aitrc.kaist.ac.kr/~vldb06/">VLDB</a> 2006 – Seul (South Korea)
          </li>
          <li value="22"><strong>A logic-based approach to cache answerability for XPath queries</strong> (<a href="/talks/XSym06_slides.pdf" target="_blank">slides</a>)<br>
          <a href="http://xsym07.ethz.ch/XSym06.html">XSym</a> 2006 – Seul (South Korea)
          </li>
          <li value="21"><strong>A new cryptographic hash function based on the cellular automaton rule 30</strong> (<a href="/talks/Nks2006.pdf" target="_blank">slides</a>)<br>
          <a href="http://www.wolframscience.com/summerschool/2006/alumni/">New Kind Of Science</a> 2006 – Brown University, Providence (USA)
          </li>
          <li value="20"><strong>XCheck, a benchmark checker for XML query processors</strong> (<a href="/talks/XCheck_slides.pdf" target="_blank">slides</a>)<br>
          <a href="http://www.unich.it">Università “G.D’Annunzio”</a> 2006 – Pescara (Italy)
          </li>
        </ol>
        <h2>2005</h2>
        <ol>
          <li value="19"><strong>Risoluzione efficiente di interrogazioni XPath su documenti XML con attributi e riferimenti</strong> (<a href="/talks/EngineXPath.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.unich.it">Università “G.D’Annunzio”</a> 2005 – Pescara (Italy)
          </li>
        </ol>
        <h2>2004</h2>
        <ol>
          <li value="18"><strong>Crittografia quantistica: fantascienza o realtà?</strong> (<a href="/talks/moca2004.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://moca.olografix.org/moca2004/">Metro Olografix Hacker Camp</a> – 2004 – Pescara (Italy)
          </li>
          <li value="17"><strong>Misure minime di sicurezza informatica del nuovo codice della privacy (D.Lgs. 196/2003)</strong> (<a href="/talks/webbit04.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">Webb.it</a> 2004 – Padova (Italy)
          </li>
        </ol>
        <h2>2003</h2>
        <ol>
          <li value="16"><strong>Introduzione allo sviluppo di applicazioni sicure</strong> (<a href="/talks/linuxday2003.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.linuxday.it/">Linux Day</a> 2003 – Teramo (Italy)
          </li>
          <li value="15"><strong>PHP e crittografia: introduzione all’utilizzo delle librerie mcrypt e mhash</strong> (<a href="/talks/phpday_2003.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.phpday.it">PHPDay</a> 2003 – Università “Tor Vergata” Roma (Italy)
          </li>
          <li value="14"><strong>Il progetto GnuPG e la crittografia Open Source</strong> (<a href="/talks/mocm_2003.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://storico.olografix.org/mocm2003/index2.html">Metro Olografix Crypto Meeting</a> 2003 – Pescara (Italy)
          </li>
          <li value="13"><strong>Crittografia è sinonimo di sicurezza?</strong> (<a href="/talks/RoboCup2003.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.robocup.org/">RoboCup</a> 2003 – Padova (Italy)
          </li>
          <li value="12"><strong>Navigare… in sicurezza, come non cadere nelle trappole della rete</strong> (<a href="/talks/Feem2003.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.feem.it/">Fondazione Eni Enrico Mattei</a> 2003 – Roma (Italy)
          </li>
          <li value="11"><strong>Introduzione alle tabelle hash</strong> (<a href="/talks/tabellehash.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.unich.it">Università degli Studi “G.d’Annunzio”</a> 2003 – Pescara (Italy)
          </li>
        </ol>
        <h2>2002</h2>
        <ol>
          <li value="10"><strong>Mantenere i propri segreti: l’utilizzo della crittografia da parte del professionista</strong> (<a href="/talks/iclc2002.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">Italian Cyberspace Law Conference</a> 2002 – Bologna (Italy)
          </li>
          <li value="9"><strong>Crittografia Open Source ed il progetto GnuPG</strong> (<a href="/talks/linuxday2002.pdf" target="_blank">PDF 532 Kb</a>)<br>
          <a href="http://www.linuxday.it/">Linux Day</a> 2002 – Facoltà di Scienze – Università dell’Aquila (Italy)
          </li>
          <li value="8"><strong>Un’introduzione alla crittografia Open Source</strong> (<a href="/talks/Smau2002.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.smau.it">Smau</a> 2002 – Ethical Hacker’s Speech, II – Milano (Italy)
          </li>
          <li value="7"><strong>Come affidare la privacy ad un’equazione matematica</strong> (<a href="/talks/Mensa2002.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.mensa.it/">Mensa Brain</a> 2002 – Francavilla al Mare, Chieti (Italy)
          </li>
          <li value="6"><strong>Introduzione alla crittografia ed alla crittoanalisi</strong> (<a href="/talks/webbit2002.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">Webbit</a> 2002 – Padova (Italy)
          </li>
          <li value="5"><strong>La crittografia nell’era Internet</strong> (<a href="/talks/italianwebawards2002.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.premiowebitalia.it/">Italian Web Awards</a> 2002 – Francavilla al Mare, Chieti (Italy)
          </li>
        </ol>
        <h2>2001</h2>
        <ol>
          <li value="4"><strong>Un’introduzione alla crittografia ed alla crittoanalisi</strong> (<a href="/talks/iclc2001.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">Italian Cyberspace Law Conference</a> 2001 – Bologna (Italy)
          </li>
        </ol>
        <h2>2000</h2>
        <ol>
          <li value="3"><strong>Il progetto GnuPg e la crittografia Open Source</strong> (<a href="/talks/lime2000.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">LiMe</a> 2000 – Università “La Sapienza” di Roma (Italy)
          </li>
          <li value="2"><strong>Il progetto GnuPg e la crittografia Open Source</strong> (<a href="/talks/linuxmeeting2000.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="#">Linux Meeting</a> 2000 – Università di Bologna (Italy)
          </li>
          <li value="1"><strong>Introduzione agli aspetti tecnico/matematici della crittografia</strong> (<a href="/talks/hackmeeting2000.pdf" target="_blank">slides</a> in Italian)<br>
          <a href="http://www.hackmeeting.org/">HackMeeting</a> 2000 – Roma (Italy)
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>
