<?php $this->layout('layout::default', [
  'title'        => 'Contact',
  'additionalJs' => ['/js/send.js', 'https://www.google.com/recaptcha/api.js']
]) ?>

<header class="intro-header" style="background-image: url('/img/contacts-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Contact Me</h1>
                    <hr class="small">
                    <span class="subheading">Have questions? I have answers (maybe).</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
            <p>Want to get in touch with me? Fill out the form below to send me a message.</p>
            <form name="sentMessage" id="contactForm">
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Name</label>
                        <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Email Address</label>
                        <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Message</label>
                        <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br />
                <div class="row control-group">
                  <div class="g-recaptcha" data-sitekey="6LcxaRMUAAAAAL4wWr5X_DP12GDeH6ZJDY4iaTFe"></div>
                </div>
                <br />
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="button" id="sendForm" class="btn btn-default">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
