<?php $this->layout('layout::default', [
  'title'         => $title,
  'additionalJs'  => ['/js/highlight/highlight.pack.js', '/js/highlight.js'],
  'additionalCss' => ['/js/highlight/styles/agate.css']
]) ?>

<header class="intro-header" style="background-image: url('/img/post/<?=$this->e($img)?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><?=$this->e($title)?></h1>
                    <hr class="post">
                    <span class="subheading"><?=$this->e($sub)?></span>
                    <span class="meta">Posted by <a rel="author" href="/about-me">Enrico Zimuel</a> on <?php echo date("F d, Y", strtotime($date)) ?></span>
                </div>
            </div>
        </div>
    </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <?=$content?>
      </div>
    </div>
  </div>
</article>
