<?php $this->layout('layout::default', ['title' => 'Publications']) ?>

<header class="intro-header" style="background-image: url('/img/publications-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Publications</h1>
                    <hr class="small">
                    <span class="subheading">Academic and technical articles</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <p>Here is reported a list of my academic and technical articles.</p>
          <ol>
            <li value="22">V. Peter, E. Zimuel. <em><strong>LLM e didattica: few-shot prompting</strong></em>, ICT Ed Magazine (in Italian), Anno VII, N° 3, October 2024, p. 10-14, ISSN 2611-4259 (<a href="https://www.ictedmagazine.com/index.php/argomenti/intelligenza-artificiale-e-nuove-frontiere/490-llm-e-didattica-few-shot-prompting.html">Read the article</a>)</li>
            <li value="21">E. Zimuel. <em><strong>Programming Elasticsearch with PHP</strong></em>, php[architect], Vol 20, Issue 7, July 2021, p. 3-12, ISSN 1709-7169 (<a href="https://www.phparch.com/article/programming-elasticsearch-with-php/">Read the article</a>)</li>
            <li value="20">E. Zimuel. <em><strong>Cryptography best practices in PHP</strong></em>, php[architect], Vol 16, Issue 5, May 2017, p. 16-20, ISSN 1709-7169 (<a href="https://www.phparch.com/magazine/2017-2/may/">Read the article</a>)</li>
            <li value="19">E. Zimuel. <em><strong>Encryption and authentication in PHP 7</strong></em>, Software Developer’s Journal, Vol 6. No 2, Issue Feb 2017. ISSN 1734-3933 (<a href="/doc/Encryption_and_authentication_in_PHP7.pdf">Read the article</a>)</li>
            <li value="18">S. Basso, J. C. De Martin, G. Futia, E. Zimuel. <em><strong>The NeuViz Data Visualization Tool for Visualizing Internet-Measurements Data</strong></em>, Mondo Digitale, n. 49, ISSN 1720-898X, 2014 (<a href="http://mondodigitale.aicanet.net/2014-1/internet_cloud_e_web_domain/05_FUTIA.pdf">Read the article</a>)</li>
            <li value="17">E. Zimuel. <em><strong>Speed up Joomla! with Zend Server Free Edition.</strong></em>, Software Developer’s Journal, Vol. 2, No. 15, Issue 15/2013. ISSN 1734-3933</li>
            <li value="16">S. Basso, J. C. De Martin, G. Futia, E. Zimuel. <em><strong>Visualizing Internet-Measurements Data for Research Purposes: the NeuViz Data Visualization Tool</strong></em>, Proceedings of 50th Congresso Nazionale AICA, ISBN 9788898091164, 2013 (<a href="http://nexa.polito.it/aica-2013-neuviz">Read the article</a>)</li>
            <li value="15">E. Zimuel. <em><strong>Cryptography in PHP. How to protect sensitive data in PHP using cryptography</strong></em>, Web &amp; PHP Magazine. Issue 2/2012, p. 16-23 (<a href="https://entwickler.de/wp-content/uploads/2012/04/WPM2_12_final.pdf" target="_blank">Read the article</a>)</li>
            <li value="14">L. Afanasiev, M. Franceschet, M. Marx, E. Zimuel. <em><strong>XCheck: a platform for benchmarking XQuery engines (demonstration)</strong></em>, Proceedings of the 32nd international conference on Very large data bases, <a href="http://www.vldb.org/dblp/db/conf/vldb/vldb2006.html" target="_blank">VLDB 2006</a>, Seoul, Korea, p. 1247-1250, 2006. (<a href="/doc/vldb06.pdf" target="_blank">Read the article in Pdf 362 Kb</a>)</li>
            <li value="13">M. Franceschet, E. Zimuel. <em><strong>A logic-based approach to cache answerability for XPath queries</strong></em>, 4th International XML Database Symposium, XSym 2006, Seoul, Korea. Database and XML Technologies, Lecture Notes in Computer Science Vol. 4156, Springer Edizioni, p. 46-60, 2006. (<a href="/doc/xsym06.pdf" target="_blank">Read the article in Pdf 170 Kb</a>)</li>
            <li value="12">M. Franceschet, E. Zimuel. <em><strong>Modal logic and navigational XPath: an experimental comparison</strong></em>, Proceedings of the 4th Workshop Methods for Modalities, <a href="http://m4m.loria.fr/M4M4/workshop.html" target="_blank">M4M 2005</a>, p. 156-172, 2005. (<a href="/doc/m4m05.pdf" target="_blank">Read the article in Pdf 143 Kb</a>)</li>
            <li value="11">M. Franceschet, E. Zimuel. <em><strong>Modal logic and navigational XPath: an experimental comparison</strong></em>, Technical Report R-2005-001, Science Department, University “G.D’Annunzio” of Chieti – Pescara, pagg 40, 2005. (<a href="/doc/R-2005-001.pdf" target="_blank">Read the report in Pdf 217 Kb</a>)</li>
            <li value="10">E. Zimuel. <em><strong>Risoluzione efficiente di interrogazioni XPath su documenti XML con attributi e riferimenti</strong></em>, Thesis degree (in Italian). University “G.D’Annunzio” di Chieti – Pescara, 2005 (<a href="/doc/Tesi_zimuel.pdf" target="_blank">Read the Thesis in Pdf 632 Kb</a>)</li>
            <li value="9">E. Zimuel. <em><strong>Introduzione alla crittografia open source</strong></em>, Linux &amp; Co. (in Italian), Piscopo Publisher, Num. 27-28,  ISSN 1129-2296, 2002. (<a href="/doc/introduzione_crittografia_os.pdf" target="_blank">Read the article in Pdf 415 Kb</a>)</li>
            <li value="8">E. Zimuel. <em><strong>Introduzione alla crittografia e alla crittoanalisi</strong></em>, Ciberspazio e Diritto – Cyberspace and Law (in Italian), Vol. 3, Num. III/IV, p. 533-545, 2001, Mucchi Publisher, Modena</li>
            <li value="7">E. Zimuel. <em><strong>La scienza delle scritture segrete</strong></em>, Computer Programming (in Italian), Num. 73, Infomedia Publisher, ISSN 1123-8526, 1998.</li>
            <li value="6">E. Zimuel. <em><strong>Speciale VGA: la programmazione della scheda grafica</strong></em>, Computer Programming (in Italian), Num. 13, Infomedia Publisher, ISSN 1123-8526, 1993. (<a href="/doc/programmazione_vga.pdf" target="_blank">Read the article in Pdf 14 MB</a>)</li>
            <li value="5">E. Zimuel. <em><strong>Gestione risorse, gestione del buffer di tastiera</strong></em>, Computer Programming (in Italian), Num. 12, Infomedia Publisher, ISSN 1123-8526, 1993.</li>
            <li value="4">E. Zimuel. <em><strong>Speciale sul mouse: una unit in Turbo Pascal per la gestione del mouse</strong></em>, Computer Programming (in Italian), Num. 9, Infomedia Publisher, ISSN 1123-8526, 1992.</li>
            <li value="3">E. Zimuel. <em><strong>Programmare il mouse</strong></em>, Computer Programming (in Italian), Num. 5-6, Infomedia Publisher, ISSN 1123-8526, 1992.</li>
            <li value="2">A. Taronna, E. Zimuel. <em><strong>Sistemi e microprocessori 8-16/32 bit</strong></em>, Computer Programming (in Italian), Num. 4, Infomedia Publisher, ISSN 1123-8526, 1992.</li>
            <li value="1">E. Zimuel. <em><strong>Memoria video: esplorando la memoria video</strong></em>, Computer Programming (in Italian), Num. 3, Infomedia Publisher, ISSN 1123-8526, 1991.</li>
          </ol>
        </div>
    </div>
  </div>
</div>
