sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' && "$(php --version | grep xdebug -ci)" -ge 1 ]]; then phpenv config-rm xdebug.ini ; fi

install:
  - travis_retry composer install
  - composer show
