<?php $this->layout('layout::default', ['title' => sprintf('%d %s', $status, $reason)]) ?>


<header class="intro-header" style="background-image: url('/img/error-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Error</h1>
                </div>
            </div>
        </div>
    </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <h1>Oops! This is awkward.</h1>
        <p>We encountered a <?=$this->e($status)?> <?=$this->e($reason)?> error.</p>
      </div>
    </div>
  </div>
</article>
