<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Enrico Zimuel, software engineer since 1996. Open source contributor, TEDx and international speakers about programmings, author of books and articles.">
    <meta name="keywords" content="developer, programmer, software, programming, hacker, open source, tedx, web, cryptography, applied cryptography, cryptanalysis, php, javascript, node.js, zend framework, apigility">
    <meta name="author" content="Enrico Zimuel">
    <meta name="verify-v1" content="bTeIQmLAmw7y/jy+pfVxXYYm9NqFscBMmw2jEVIqv4k=">
    <meta name="wot-verification" content="7ca48dd483cee64e4099"/>

    <title>Enrico Zimuel - Software developer since 1996, speaker, author</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="/css/clean-blog.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Highlight syntax -->
    <link rel="stylesheet" href="/js/highlight/styles/agate.css">
    <script src="/js/highlight/highlight.pack.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <!-- Navigation -->
      <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
          <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header page-scroll">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      Menu <i class="fa fa-bars"></i>
                  </button>
                  <a class="navbar-brand" href="/">Enrico Zimuel</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                      <li>
                          <a href="/">Home</a>
                      </li>
                      <li>
                          <a href="/about-me">About</a>
                      </li>
                      <li>
                          <a href="/blog">Blog</a>
                      </li>
                      <li>
                          <a href="/publications">Publications</a>
                      </li>
                      <li>
                          <a href="/books">Books</a>
                      </li>
                      <li>
                          <a href="/conferences">Conferences</a>
                      </li>
                      <li>
                          <a href="/contact">Contact</a>
                      </li>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

      <!-- Page Header -->
      <?php echo $this->section('content')?>

      <!-- Footer -->
          <footer>
              <div class="container">
                  <div class="row">
                      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                          <ul class="list-inline text-center">
                              <li>
                                  <a href="https://twitter.com/ezimuel">
                                      <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                      </span>
                                  </a>
                              </li>
                              <li>
                                  <a href="https://www.linkedin.com/in/ezimuel">
                                      <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                      </span>
                                  </a>
                              </li>
                              <li>
                                  <a href="https://github.com/ezimuel">
                                      <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                      </span>
                                  </a>
                              </li>
                          </ul>
                          <p class="copyright text-muted">
                            Copyright &copy; 2001-<?php echo date("Y") ?> by Enrico Zimuel - <a href="/privacy-policy">Privacy Policy</a><br />
                            Made with <i class="fa fa-heart"></i> using <a href="https://github.com/zendframework/zend-expressive">zend-expressive</a> and <a href="http://php.net/">PHP</a>.
                          </p>
                      </div>
                  </div>
              </div>
          </footer>

          <!-- jQuery -->
          <script src="/js/jquery/jquery.min.js"></script>

          <!-- Bootstrap Core JavaScript -->
          <script src="/js/bootstrap/js/bootstrap.min.js"></script>

          <!-- Contact Form JavaScript -->
          <script src="/js/jqBootstrapValidation.js"></script>
          <script src="/js/contact_me.js"></script>

          <!-- Theme JavaScript -->
          <script src="/js/clean-blog.min.js"></script>

          <script>hljs.initHighlightingOnLoad();</script>

          <?php $this->insert('layout::google-analytics'); ?>
</body>
</html>
